spring.application.name=Banco

server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:mariadb://localhost:3310/banco
spring.datasource.username=root
spring.datasource.password=root1
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.threads.virtual.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${SERVER_PORT:8081}
server.error.include-stacktrace=always

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG
logging.level.org.springframework.data=INFO
logging.level.org.hibernate=INFO

jwt.secret=${JWT_SECRET:troque-esta-chave}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.issuer=${JWT_ISSUER:bancoBrasilInvestidores}

session.timeout.minutes=${SESSION_TIMEOUT_MINUTES:30}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devebsjunior@gmail.com
spring.mail.password=utrrvjbroxeoyyeg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.open-in-view=false



