spring.application.name=Banco

#################################################

# DATASOURCE

#################################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#################################################

# JPA / HIBERNATE

#################################################

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

#################################################
# VIRTUAL THREADS (JAVA 21)
#################################################

spring.threads.virtual.enabled=true

#################################################
# SWAGGER
#################################################

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#################################################
# SERVER
#################################################

server.port=${SERVER_PORT:8081}
server.error.include-stacktrace=always

#################################################
# LOGGING
#################################################

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG

#################################################
# JWT
#################################################

jwt.secret=${JWT_SECRET:troque-esta-chave}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.issuer=${JWT_ISSUER:bancoBrasilInvestidores}

#################################################
# SESSION
#################################################

session.timeout.minutes=${SESSION_TIMEOUT_MINUTES:30}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}